### PR TITLE
Add parser for boost logging

### LINKED ISSUE #36: feature: Add parser for boost logging
Most close to logcat config would be this configuration:
"%TimeStamp% %ProcessID% %ThreadID% %Process%: %Message%"

### PR DESCRIPTION
**Pull request by miklelappo**
Allow projects using boost logging to use nice rogcat colours

The setup for boost logging should look like this:
"%TimeStamp% %ProcessID% %ThreadID% %Process%: %Message%"

Closes #36

### CODE REVIEW

**Review by flxo — COMMENTED** [review]
Thanks for the PR. 
The parsing is so repetitive. Think it's time for a general purpose parser that uses format strings ala timestamps.

**Comment by flxo** [comment]
Is there somewhere a definition of the "boot format"?

**Comment by miklelappo** [comment]
Boost logging is setup via logging.ini file and can take many different forms. The proposed format is as close as possible to android one which is the best from my ppov.

`Format= "%TimeStamp% %ProcessID% %ThreadID% %Process%: %Message%"`

**Comment by flxo** [comment]
Puh. This requires very detailed knowledge in order to get setup. My feeling for the future is more to get rid of formats and focus on the formats used by `logcat`. Started this with https://github.com/flxo/rogcat/commit/281dc3ab633536cc8d3d99d16861c27cc799e5f1.

**Comment by flxo** [comment]
C

**Pull request closed without merging**
